feature/improved-termination-notification
HedvigInsurance/product-pricing pull request #612
Opened 2020-08-18 19:50 UTC by johantjellden

Send events to notification-service on termination events
* Think about should we include the terminationdate updated event

2020-08-25 12:56 UTC, palmenhq approved these changes
Looks fine! Just one thought

2020-08-25 12:56 UTC, palmenhq commented on src/main/java/com/hedvig/productPricing/service/serviceIntegration/notificationService/dto/EventRequest.kt
> +  val owningMemberId: String,
idk if this is too late to change but isn't `holderMemberId` what we use everywhere else?

2020-08-25 13:00 UTC, AlexSJ1990 requested changes

2020-08-25 13:00 UTC, AlexSJ1990 commented on src/main/java/com/hedvig/productPricing/service/serviceIntegration/notificationService/NotificationServiceClient.java
>    @PostMapping("/_/events/contractRenewalQueued")
shall we add the deprecated annotation to these

2020-08-25 13:00 UTC, AlexSJ1990 commented on src/main/java/com/hedvig/productPricing/service/serviceIntegration/notificationService/NotificationServiceClient.java
> +  void sendContractTerminatedEvent(@NotNull ContractTerminatedEvent contractTerminatedEvent, @RequestHeader("Request-Id") String identifier);
maybe `void sendEvent(NotNull EventRequest eventRequest, RequestHeader("Request-Id") String identifier)`

2020-08-25 13:09 UTC, vonElfvin reviewed
Added some comments

2020-08-25 13:09 UTC, vonElfvin commented on src/main/java/com/hedvig/contract/customerio/EventListener.kt
> +      sendCancellation(event, timestamp, event.newTerminationDate, event.contractId, eventMessage.identifier)
I wouldn't send an email if we change the date I think? Maybe update some attribute though? 🤔

2020-08-25 13:09 UTC, vonElfvin commented on src/main/java/com/hedvig/productPricing/service/serviceIntegration/notificationService/NotificationServiceImpl.kt
> +      logger.error("Could not update notification-service for event $contractId", ex)
```suggestion
      logger.error("Could not update notification-service for event $identifier (contractId=$contractId)", ex)
```

2020-08-25 13:09 UTC, vonElfvin commented on src/main/java/com/hedvig/productPricing/service/serviceIntegration/notificationService/dto/EventRequest.kt
> +}
Do we need this? Or maybe, in the future, this should be in some kind of package?

2020-08-26 05:38 UTC, johantjellden commented on src/main/java/com/hedvig/productPricing/service/serviceIntegration/notificationService/dto/EventRequest.kt
> +  val owningMemberId: String,
Yup to late, these DTO are already in use else where.

2020-08-26 05:46 UTC, johantjellden commented on src/main/java/com/hedvig/contract/customerio/EventListener.kt
> +      sendCancellation(event, timestamp, event.newTerminationDate, event.contractId, eventMessage.identifier)
Why not is it not good to now that we now have a new cancellationdate?

2020-08-26 06:09 UTC, AlexSJ1990 approved these changes

2020-08-26 06:10 UTC, merged